# **Swiss Railway:** Complex Network Creation

In [ ]:
import pandas as pd

## **Data Analysis**

We have obtained two csv files from the website https://figshare.com/articles/dataset/Four_representations_of_the_Swiss_railway_network/29609615/2. One of them contains the data about the nodes and the other about the edges that connect those nodes.

In the following sections we will enter into detail about each one of those files.

### Node data

The node data of our network is in the file `nodelist.csv`. Each node represents one of the 1626 stations of the Swiss Railway network for all the rail companys in the country. Moreover, we have information available of the city where the station is located, the company that controls the station, the geographic location and about the average daily traffic of each node.

In [9]:
df_nodes = pd.read_csv("data/nodelist.csv", delimiter=';')

display(df_nodes)
display(df_nodes.dtypes)

,BPUIC,STATION_NAME,CANTON,MUNICIPALITY,COMPANY,LONGITUDE,LATITUDE,ELEVATION,AVG_DAILY_TRAFFIC,AVG_DAILY_TRAFFIC_WEEKDAYS,AVG_DAILY_TRAFFIC_WEEKENDS,TRAFFIC_VALID
0,8500010,Basel SBB,Basel-Stadt,Basel,Swiss Federal Railways SBB,7.589563,47.547412,276.75,98600.0,105900.0,81900.0,True
1,8500016,Basel St. Johann,Basel-Stadt,Basel,Swiss Federal Railways SBB,7.572529,47.570306,260.50,90.0,100.0,60.0,True
2,8500020,Muttenz,Basel-Landschaft,Muttenz,Swiss Federal Railways SBB,7.647894,47.533591,280.80,5700.0,7000.0,2800.0,True
3,8500021,Pratteln,Basel-Landschaft,Pratteln,Swiss Federal Railways SBB,7.690817,47.522669,289.60,8500.0,9900.0,5200.0,True
4,8500022,Frenkendorf-Füllinsdorf,Basel-Landschaft,Frenkendorf,Swiss Federal Railways SBB,7.719111,47.501470,310.96,3600.0,4100.0,2300.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...
1621,8593774,La Faverge,Vaud,Ormont-Dessus,Transports Publics du Chablais,7.147120,46.354930,1147.30,NaN,NaN,NaN,False
1622,8593775,Les Nicolets,Vaud,Ormont-Dessus,Transports Publics du Chablais,7.119540,46.354460,1096.60,NaN,NaN,NaN,False
1623,8593776,Plan Morier,Vaud,Ormont-Dessus,Transports Publics du Chablais,7.129200,46.353570,1108.60,NaN,NaN,NaN,False
1624,8594258,Langenthal Industrie Nord,Bern,Langenthal,Aare Seeland mobil (rvo),7.786471,47.228557,458.00,NaN,NaN,NaN,False
1625,8595245,Areuse Littorail,Neuchâtel,Boudry,Transports Publics Neuchâtelois SA (tn),6.853057,46.954495,438.20,NaN,NaN,NaN,False

BPUIC                           int64
STATION_NAME                   object
CANTON                         object
MUNICIPALITY                   object
COMPANY                        object
LONGITUDE                     float64
LATITUDE                      float64
ELEVATION                     float64
AVG_DAILY_TRAFFIC             float64
AVG_DAILY_TRAFFIC_WEEKDAYS    float64
AVG_DAILY_TRAFFIC_WEEKENDS    float64
TRAFFIC_VALID                    bool
dtype: object

### Edges data

The edges data of our network is in the file `edgelist_SoCha.csv`. Each row represents a directed edge between two stations connected by a direct service that requires no train changes. Moreover, we also have the average time duration of each interstation.

In [4]:
df_edges = pd.read_csv("data/edgelist_SoCha.csv", delimiter=';')

display(df_edges)
display(df_edges.dtypes)

        BPUIC1   BPUIC2  NUM_CONNECTIONS  AVG_DURATION
0      8503000  8500010               88         63.81
1      8503000  8500090               14         81.36
2      8500010  8500090               67          6.07
3      8500090  8500010               67          6.39
4      8500090  8503000               10        100.00
...        ...      ...              ...           ...
37940  8503464  8503466               37          6.00
37941  8503464  8503467               37          9.03
37942  8503465  8503466               37          2.00
37943  8503465  8503467               37          5.03
37944  8503466  8503467               37          2.00

[37945 rows x 4 columns]

BPUIC1               int64
BPUIC2               int64
NUM_CONNECTIONS      int64
AVG_DURATION       float64
dtype: object